# Claves del proyecto
sonar.projectKey=Apilibraryfng
sonar.projectName=Apilibraryfng
sonar.token=sqp_7ed16b806c265b68e3c3519ea8bdd95bd450e96d

# Dirección de tu servidor local
sonar.host.url=http://localhost:9000

# Ruta de tu código de Angular (analiza la carpeta src)
sonar.sources=src

# Exclusiones para Angular (evita analizar pruebas y archivos autogenerados)
sonar.exclusions=src/**/*.spec.ts, node_modules/**, .angular/**, dist/**